//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TAUSDataProvider.Resources {
    using System;
    using System.Globalization;
    using System.Resources;

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TAUSResources {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TAUSResources() {
        }
        

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    var temp = new global::System.Resources.ResourceManager("TAUSDataProvider.Resources.TAUSResources", typeof(TAUSResources).Assembly);
                    resourceMan = temp;
                }

                return resourceMan;
            }
        }
        

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static CultureInfo Culture {
            get {
                return resourceCulture;
            }

            set {
                resourceCulture = value;
            }
        }
        

        /// <summary>
        ///   Looks up a localized string similar to Content Type for the translation.
        /// </summary>
        public static string PropertyContentTypeDescription {
            get {
                return ResourceManager.GetString("PropertyContentTypeDescription", resourceCulture);
            }
        }
        

        /// <summary>
        ///   Looks up a localized string similar to Content Type.
        /// </summary>
        public static string PropertyContentTypeDisplayName {
            get {
                return ResourceManager.GetString("PropertyContentTypeDisplayName", resourceCulture);
            }
        }
        

        /// <summary>
        ///   Looks up a localized string similar to Industry that provided the translation.
        /// </summary>
        public static string PropertyIndustryDescription {
            get {
                return ResourceManager.GetString("PropertyIndustryDescription", resourceCulture);
            }
        }
        

        /// <summary>
        ///   Looks up a localized string similar to Industry.
        /// </summary>
        public static string PropertyIndustryDisplayName {
            get {
                return ResourceManager.GetString("PropertyIndustryDisplayName", resourceCulture);
            }
        }
        

        /// <summary>
        ///   Looks up a localized string similar to Owner of the translation.
        /// </summary>
        public static string PropertyOwnerDescription {
            get {
                return ResourceManager.GetString("PropertyOwnerDescription", resourceCulture);
            }
        }
        

        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        public static string PropertyOwnerDisplayName {
            get {
                return ResourceManager.GetString("PropertyOwnerDisplayName", resourceCulture);
            }
        }
        

        /// <summary>
        ///   Looks up a localized string similar to Product that uses the translation.
        /// </summary>
        public static string PropertyProductDescription {
            get {
                return ResourceManager.GetString("PropertyProductDescription", resourceCulture);
            }
        }
        

        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string PropertyProductDisplayName {
            get {
                return ResourceManager.GetString("PropertyProductDisplayName", resourceCulture);
            }
        }
        

        /// <summary>
        ///   Looks up a localized string similar to Company that provided the translation.
        /// </summary>
        public static string PropertyProviderDescription {
            get {
                return ResourceManager.GetString("PropertyProviderDescription", resourceCulture);
            }
        }
        

        /// <summary>
        ///   Looks up a localized string similar to Provider.
        /// </summary>
        public static string PropertyProviderDisplayName {
            get {
                return ResourceManager.GetString("PropertyProviderDisplayName", resourceCulture);
            }
        }
        

        /// <summary>
        ///   Looks up a localized string similar to The required credentials were not found in the Credential Manager service..
        /// </summary>
        public static string ProviderCredentialError {
            get {
                return ResourceManager.GetString("ProviderCredentialError", resourceCulture);
            }
        }
        

        /// <summary>
        ///   Looks up a localized string similar to This is a TAUS DATA provider that works with the Multilingual App Toolkit.  Please review the documentation for implementation details.
        /// </summary>
        public static string ProviderDescription {
            get {
                return ResourceManager.GetString("ProviderDescription", resourceCulture);
            }
        }
        

        /// <summary>
        ///   Looks up a localized string similar to TAUS DATA provider.
        /// </summary>
        public static string ProviderDisplayName {
            get {
                return ResourceManager.GetString("ProviderDisplayName", resourceCulture);
            }
        }
    }
}
